---
- name: Amp playbook
  hosts: all
  become: yes
  tasks:
    - name: Add amp user
      ansible.builtin.user:
        name: amp
        shell: /bin/bash
    - name: Add Cubecoders signing key
      ansible.builtin.apt_key:
        url: http://repo.cubecoders.com/archive.key
        state: present
    - name: Add Cubecoders repository
      ansible.builtin.apt_repository:
        repo: deb http://repo.cubecoders.com/ debian/
        state: present
    - name: Install required packages
      ansible.builtin.apt:
        update_cache: yes
        name:
          - acl
          - ampinstmgr